[package]
name = "table-traits"
description = "Common table-related traits."
version = "0.0.0"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/SirWindfield/table-traits"
authors = ["Sven Lechner <SirWindfield@users.noreply.github.com>"]
edition = "2018"
